module.exports = {
  apps: [
    {
      name: 'mud-game-test',
      script: 'main.js',
      args: '100',
      cwd: '/home/mud/mud',
      env: {
        NODE_ENV: 'production',
        SERVER_ID: '100',
        WS_PORT: '31300',
        ADMIN_IPC_PORT: '31303',
      },
      log_date_format: 'YYYY-MM-DD HH:mm:ss',
      error_file: './log/pm2-game-test-error.log',
      out_file: './log/pm2-game-test-out.log',
      max_restarts: 10,
      restart_delay: 5000,
      max_memory_restart: '800M',
      kill_timeout: 10000,
      watch: false,
    },
    {
      name: 'mud-game',
      script: 'main.js',
      args: '200',
      cwd: '/home/mud/mud',
      env: {
        NODE_ENV: 'production',
        SERVER_ID: '200',
        WS_PORT: '31301',
        ADMIN_IPC_PORT: '31304',
      },
      log_date_format: 'YYYY-MM-DD HH:mm:ss',
      error_file: './log/pm2-game-error.log',
      out_file: './log/pm2-game-out.log',
      max_restarts: 10,
      restart_delay: 5000,
      max_memory_restart: '800M',
      kill_timeout: 10000,
      watch: false,
    },
    {
      name: 'mud-web',
      script: 'web.js',
      cwd: '/home/mud/mud',
      env: {
        NODE_ENV: 'production',
      },
      log_date_format: 'YYYY-MM-DD HH:mm:ss',
      error_file: './log/pm2-web-error.log',
      out_file: './log/pm2-web-out.log',
      max_restarts: 10,
      restart_delay: 5000,
      max_memory_restart: '500M',
      watch: false,
    },
  ],
};
