
const fs_sync = require("fs");
const fs = fs_sync.promises;

const DB = __CONFIG.DB;

module.exports = {
    close: function () {
        return DB.close();
    },
    getRoles: function (userid, server) {
        return DB.getRoles(userid, server);
    },
    addRole: async function (role) {
        return await DB.addRole(role);
    },
    deleteRole: function (userid, roleid) {
        return DB.deleteRole(userid, roleid);
    },
    saveRoleSync: function (role) {
        return DB.saveRoleSync(role);
    },
    saveRole: function (role) {
        if (!this._pendingRoleSaves) this._pendingRoleSaves = new Set();
        const pending = this._saveRole(role);
        this._pendingRoleSaves.add(pending);
        pending.then(() => this._pendingRoleSaves.delete(pending), () => this._pendingRoleSaves.delete(pending));
        return pending;
    },
    drainRoleSaves: async function () {
        const results = await Promise.allSettled([...(this._pendingRoleSaves || [])]);
        return results.every(result => result.status === 'fulfilled');
    },
    _saveRole: async function (role) {
        try {
            const result = DB.saveRoleSync ? DB.saveRoleSync(role) : await DB.saveRole(role);
            if (!result || result.changes !== 1) throw new Error('角色存档未更新');
            return result;
        } catch (error) {
            // Retain the last logout snapshot without retrying an old write
            // over a later session. Recovery is an explicit operator action.
            const dir = __PATH.DATA + 'bak';
            await fs.mkdir(dir, { recursive: true });
            const file = dir + '/failed-' + Date.now() + '-' + require('crypto').randomBytes(6).toString('hex') + '.json';
            await fs.writeFile(file, JSON.stringify([role]), { encoding: 'utf8', flag: 'wx' });
            throw error;
        }
    },
    // 登录时刷新最后活跃时间，供后台"活跃玩家"统计使用
    touchRole: function (id) {
        return DB.touchRole(id);
    },
    saveRoles: async function (roles) {
        const dt = new Date();
        const backupPath = __PATH.DATA + "bak/data" + dt.toISOString().replace(/[-:.TZ]/g, "") + '-' + require('crypto').randomBytes(6).toString('hex') + ".json";
        const failures = [];
        const savedRoles = [];
        const backupRoles = [];
        for (let role of (roles || [])) {
            try {
                // Character IDs are generated by UTIL.create_id() and are
                // short base36 strings (not positive numbers).  Reject only
                // missing/oversized IDs and invalid user IDs so normal player
                // saves are not silently skipped.
                const roleId = role && role.id !== undefined && role.id !== null ? String(role.id) : "";
                const userId = role && Number(role.userid);
                if (!role || !roleId || roleId.length > 40 ||
                    !Number.isSafeInteger(userId) || userId <= 0 || typeof role.data !== "string")
                    throw new Error("角色存档格式无效");
                backupRoles.push(role);
                const result = DB.saveRoleSync ? DB.saveRoleSync(role) : await DB.saveRole(role);
                if (!result || result.changes !== 1)
                    throw new Error("角色不存在或数据库未更新");
                savedRoles.push(role);
            } catch (error) {
                failures.push({ id: role && role.id, error: error });
                console.error('保存角色失败：', role && role.id, error);
            }
        }
        // Write one complete, escaped JSON backup per save batch.  Appending
        // another array to an hourly file made recovery ambiguous; hand-built
        // fields could also be corrupted by quotes/newlines in titles.
        try {
            await fs.mkdir(__PATH.DATA + "bak", { recursive: true });
            // Keep every valid snapshot, including a role whose DB write
            // failed, so operators can recover the latest in-memory state.
            await fs.writeFile(backupPath, JSON.stringify(backupRoles), "utf8");
        } catch (error) {
            failures.push({ id: null, error: error });
            console.error('备份数据失败：', error);
        }
        if (failures.length) {
            const err = new Error("玩家数据保存部分失败");
            err.failures = failures;
            throw err;
        }
        return { saved: savedRoles.length, backup: backupPath };

    },
    localBak: function (stream, role) {
        stream.write('{id:"');
stream.write(role.id);
stream.write('",name:"');
stream.write(role.name);
stream.write('",userid:');
        stream.write(role.userid.toString());
        stream.write(',title:"');
stream.write(role.title);
stream.write('",level:');
        stream.write(role.level.toString());
        stream.write(',data:');
        stream.write(role.data);
        stream.write('},');
    },
    saveRequest: function (recs) {
        var dt = new Date();
        var f = dt.getFullYear() + "-" + (dt.getMonth() + 1) + "-" + dt.getDate();
        var path = __PATH.DATA + "req/request" + f + ".txt";
        var ary = [];
        for (var i = 0; i < recs.length; i++) {
            var r = recs[i];
            ary.push(r.time);
            ary.push(" ");
            ary.push(r.user);
            ary.push(" ");
            ary.push(r.cmd);
            ary.push("\r\n");
        }
        return fs.appendFile(path, ary.join(""));
    },
    saveLogs: function (logs) {
        var dt = new Date();
        var f = dt.getFullYear() + "-" + (dt.getMonth() + 1) + "-" + dt.getDate();
        var path = __PATH.DATA + "log/log" + f + ".txt";
        var ary = [];
        for (var i = 0; i < logs.length; i++) {
            var r = logs[i];
            ary.push(r.time);
            ary.push(" ");
            ary.push(r.user);
            ary.push(" ");
            ary.push(r.cmd);
            ary.push(" ");
            ary.push(r.msg);
            ary.push("\r\n");
        }
        return fs.appendFile(path, ary.join(""));
    },
    saveData: function (content) {
        const next = (this._dataWrite || Promise.resolve()).catch(() => {}).then(() => this._writeData(content));
        this._dataWrite = next;
        return next;
    },
    _writeData: async function (content) {
        let path = __PATH.DATA + "data.js";
        let dt = new Date();
        var f = dt.getFullYear() + "-" + (dt.getMonth() + 1) + "-" + dt.getDate();
        let _dst = __PATH.DATA + "/temp/temp" + f + ".js";
        await fs.copyFile(path, _dst);
        // 原子写入: 先写临时文件, 再重命名, 避免写入中途崩溃导致 data.js 损坏
        let tmpPath = path + '.tmp';
        let bakPath = path + '.bak';
        await fs.writeFile(tmpPath, content);
        if (await this.check_file(path)) {
            try { await fs.copyFile(path, bakPath); } catch (e) {}
        }
        await fs.rename(tmpPath, path);
    }, readData: async function () {
        let path = __PATH.DATA + "data.js";
        try {
            const data = await fs.readFile(path);
            return JSON.toObject(data);
        } catch (error) {
            console.error('[存档] 读取失败，尝试.bak备份...', error.message);
            try {
                var bakPath = path + '.bak';
                if (require('fs').existsSync(bakPath)) {
                    const bakData = await fs.readFile(bakPath);
                    console.log('[存档] 已从.bak恢复');
                    return JSON.toObject(bakData);
                }
            } catch(e) { console.error('[存档] .bak也失败:', e.message); }
        }
        throw new Error('世界主档及备份均不可读取，拒绝以空存档启动');
    },
    getRoleData: function (userid, id) {

        return DB.getData(userid, id);
    },
    change_name: function (id, name) {
        return DB.updateRoleName(id, name);
    },
    change_userid: function (id, fromuserid, touserid) {
        return DB.updateUserid(id, fromuserid, touserid);
    },
    check_file: async function (path) {
        try {
            await fs.access(path)
            return true;
        } catch (error) {
            return false;
        }
    },
    initDataDir: async function () {
        __PATH.BASE_DATA = __PATH.DATA;
        __PATH.DATA = __PATH.DATA + WORLD.SERVERID + "/";

        if (!await this.check_file(__PATH.DATA)) {
            console.log('创建备份文件夹....');
            await fs.mkdir(__PATH.DATA);
        }
        var paths = await fs.readdir(__PATH.DEF_DATA);
        for (var i = 0; i < paths.length; i++) {
            var _src = __PATH.DEF_DATA + paths[i];
            var _dst = __PATH.DATA + paths[i];
            if (!await this.check_file(_dst)) {
                var stat = await fs.stat(_src);
                if (stat.isFile()) {
                    await fs.copyFile(_src, _dst);
                    console.log('创建备份文件 ', _dst, "....");
                } else {
                    await fs.mkdir(_dst);
                    console.log('创建备份文件夹 ', _dst, "....");
                }
            }

        }
    },
    getServers: function () {
        return DB.getServers();
    }
};
